name: Build OpenJDK8 for Android

on:
  workflow_dispatch:
  schedule:
  - cron: "5 5 2,9,16,23 * *"

jobs:
  build_android:
    strategy:
      matrix:
        arch: [ "aarch32", "aarch64", "x86", "x86_64" ]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.4
    - name: Set Up JDK 8
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 8
        distribution: temurin
    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt -y install systemtap-sdt-dev gcc-multilib g++-multilib libxtst-dev libasound2-dev libelf-dev libfontconfig1-dev libx11-dev
        git clone --depth 1 --branch buildjre8 https://github.com/Vera-Firefly/android-openjdk-build
    - name: Build with CI build script
      run: |
        cd android-openjdk-build
        bash "ci_build_arch_${{matrix.arch}}.sh"
    - name: Upload JDK build output
      uses: actions/upload-artifact@v4.3.3
      with:
        name: "jdk8-${{matrix.arch}}"
        path: android-openjdk-build/jdk8*.tar.xz
    - name: Upload JRE build output
      uses: actions/upload-artifact@v4.3.3
      with:
        name: 'jre8-${{matrix.arch}}'
        path: android-openjdk-build/jre8*.tar.xz
    - name: Upload JRE debuginfo build output
      uses: actions/upload-artifact@v4.3.3
      with:
        name: "jre8-debuginfo-${{matrix.arch}}"
        path: android-openjdk-build/dizout

  pojav:
    needs: build_android
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.4
    - name: Get jre8-aarch32
      uses: actions/download-artifact@v4.1.7
      with:
        name: jre8-aarch32
        path: pojav
    - name: Get jre8-aarch64
      uses: actions/download-artifact@v4.1.7
      with:
        name: jre8-aarch64
        path: pojav
    - name: Get jre8-x86
      uses: actions/download-artifact@v4.1.7
      with:
        name: jre8-x86
        path: pojav
    - name: Get jre8-x86_64
      uses: actions/download-artifact@v4.1.7
      with:
        name: jre8-x86_64
        path: pojav
    - name: Repack JRE
      run: |
        git clone --depth 1 --branch buildjre8 https://github.com/Vera-Firefly/android-openjdk-build
        bash "android-openjdk-build/repackjre.sh" $GITHUB_WORKSPACE/pojav $GITHUB_WORKSPACE/pojav/jre8-pojav
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
          name: jre8-pojav
          path: pojav/jre8-pojav/*

  push:
    if: github.repository_owner == 'Vera-Firefly'
    needs: pojav
    runs-on: ubuntu-latest
    steps:
    - name: Set IS_MAIN_BRANCH if on main branch
      run: echo "JRE_OUTPUT=8" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get jre
      uses: actions/download-artifact@v4.1.7
      with:
        name: jre8-pojav
        path: JreOutPut

    - name: Push New Jre on this Repository
      run: |
        chmod +x push.sh
        sh push.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KEY_PASSWORD: ${{ secrets.SSH_KEY_PASSWORD }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
      shell: bash
